name: Lint API Specification File

on:
  push:
    branches: [main]

jobs:
  call-linter:
    uses: cekinmezyucel/zally/.github/workflows/validation-check-with-cli.yml@main
    with:
      file-path: api/example_api.yaml
    secrets: inherit
